_BASE_: ../../configs/Base-SSD-VGG16.yaml
MODEL:
  WEIGHTS: KODO://ImageNetPretrained/Chen-Jianhu/vgg16_reducedfc.pkl
  SSD:
    IMAGE_SIZE: 300
    FEATURE_MAP_SIZE: [38, 19, 10, 5, 3, 1]
    DEFAULT_BOX:
      SCALE:
        CONV4_3_SCALE: 0.07  # 0.1 for pascal voc and 0.07 for coco
        S_MIN: 0.15  # 0.2 for pascal voc and 0.15 for coco
        S_MAX: 0.9
      ASPECT_RATIOS: [[2], [2, 3], [2, 3], [2, 3], [2], [2]]
      CLIP: False
INPUT:
  COLOR_AUG: True
  SWAP_CHANNELS: True
  EXPAND: False
  MIN_IOU_CROP: True
  RESIZE:
    ENABLED: True
    SIZE: (300, 300)
