MODEL:
  META_ARCHITECTURE: "DeepFeatureFlow"
  FLOWNET:
    NAME: "FlowNetS"
    WEIGHTS: "KODO://FlyingChairsPretrained/JianhuChen/FlowNetS.pkl"
    PIXEL_MEAN: [0.45, 0.432, 0.411]
    PIXEL_STD: [1, 1, 1]
    NORM: ""
    NEGATIVE_SLOPE: 0.1
    FLOW_DIV: 20.
  DFF:
    FRAME_OFFSET_RANGE: [-9, 0]
    KEY_FRAME_DURATION: 10
  ROI_HEADS:
    NAME: "Res5ROIHeads"
DATASETS:
  TRAIN: ("imagenet_det_train_30classes", "imagenet_vid_train_15frames")
  TEST: ("imagenet_vid_val_videos",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.001
  STEPS: (40000,)
  MAX_ITER: 60000
INPUT:
  MIN_SIZE_TRAIN: (600,)
  MAX_SIZE_TRAIN: 1000
  MIN_SIZE_TEST: 600
  MAX_SIZE_TEST: 1000
VIS_PERIOD: 500
VERSION: 2
