_BASE_: Base-SSD-VGG16.yaml
MODEL:
  WEIGHTS: KODO://ImageNetPretrained/JianhuChen/vgg16_reducedfc.pkl
  SSD:
    IMAGE_SIZE: 512
    FEATURE_MAP_SIZE: [64, 32, 16, 8, 4, 2, 1]
    DEFAULT_BOX:
      SCALE:
        CONV4_3_SCALE: 0.04
        S_MIN: 0.1
        S_MAX: 0.9
      ASPECT_RATIOS: [[2], [2, 3], [2, 3], [2, 3], [2, 3], [2], [2]]
      CLIP: False
INPUT:
  COLOR_AUG: True
  SWAP_CHANNELS: True
  EXPAND: False
  MIN_IOU_CROP: True
  RESIZE:
    ENABLED: True
    SIZE: (512, 512)
